// GET /api/items - Get all items for an FPO
import { NextRequest, NextResponse } from 'next/server'
import { getAllItems , getUnitByCode , createItem , getCategoryById  } from '@/server/features/items/infrastructure/persistence/ItemSupabase'

import { Product, Service } from '@/server/features/items/core/entities/Item'
// GET /api/items - Get all items for an FPO

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const fpo_id = searchParams.get('fpo_id')

    if (!fpo_id) {
      return NextResponse.json(
        { error: 'fpo_id is required' },
        { status: 400 }
      )
    }

    const items = await getAllItems(fpo_id)

    if (items === null) {
      return NextResponse.json(
        { error: 'Failed to fetch items' },
        { status: 500 }
      )
    }

    return NextResponse.json({
      success: true,
      data: items,
      count: items.length
    })

  } catch (error) {
    console.error('Error in GET /api/items:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}

// POST /api/items - Create a new item
interface CreateItemRequest {
  name: string
  type: 'product' | 'service'
  category_id: string
  hsn_sac: string
  salePrice: number
  salePriceInclusive: boolean
  gstTaxPercent: number
  fpo_id: string
  
  // Product-specific fields (optional)
  purchasePrice?: number
  purchasePriceInclusive?: boolean
  unit_code?: string
  openingQuantity?: number
  openingStockDate?: string // ISO date string
  mfgDate?: string // ISO date string
  expDate?: string // ISO date string
  currentStock?: number
  barcode?: string
  discount?: {
    value: number
    type: 'fixed' | 'percent'
  }
  lowStockAlert?: number
}

export async function POST(request: NextRequest) {
  try {
    const body: CreateItemRequest = await request.json()

    // Validate required fields
    if (!body.name || !body.type || !body.category_id || !body.hsn_sac || 
        body.salePrice === undefined || body.salePriceInclusive === undefined || 
        body.gstTaxPercent === undefined || !body.fpo_id) {
      return NextResponse.json(
        { error: 'Missing required fields: name, type, category_id, hsn_sac, salePrice, salePriceInclusive, gstTaxPercent, fpo_id' },
        { status: 400 }
      )
    }

    // Validate type
    if (!['product', 'service'].includes(body.type)) {
      return NextResponse.json(
        { error: 'type must be either "product" or "service"' },
        { status: 400 }
      )
    }

    // Get category
    const category = await getCategoryById(body.category_id)
    if (!category) {
      return NextResponse.json(
        { error: 'Category not found' },
        { status: 404 }
      )
    }

    let item: Product | Service

    if (body.type === 'product') {
      // Validate product-specific required fields
      if (!body.unit_code || body.purchasePrice === undefined) {
        return NextResponse.json(
          { error: 'unit_code and purchasePrice are required for products' },
          { status: 400 }
        )
      }

      // Get unit
      const unit = await getUnitByCode(body.unit_code)
      if (!unit) {
        return NextResponse.json(
          { error: 'Unit not found' },
          { status: 404 }
        )
      }

      // Create Product instance (ID will be generated by Supabase)
      item = new Product(
        '', // Empty ID - will be generated by Supabase
        body.name,
        category,
        body.hsn_sac,
        body.salePrice,
        body.salePriceInclusive,
        body.gstTaxPercent,
        body.purchasePrice,
        body.purchasePriceInclusive || false,
        unit,
        body.openingQuantity || 0,
        body.openingStockDate ? new Date(body.openingStockDate) : null,
        body.mfgDate ? new Date(body.mfgDate) : null,
        body.expDate ? new Date(body.expDate) : null,
        body.currentStock, // Will default to opening quantity in createItem if undefined
        body.openingStockDate ? new Date(body.openingStockDate) : null, // lastStockUpdate
        body.barcode,
        body.discount,
        body.lowStockAlert
      )
    } else {
      // Create Service instance (ID will be generated by Supabase)
      item = new Service(
        '', // Empty ID - will be generated by Supabase
        body.name,
        category,
        body.hsn_sac,
        body.salePrice,
        body.salePriceInclusive,
        body.gstTaxPercent
      )
    }

    // Create item in database
    const createdItem = await createItem(item, body.fpo_id)

    if (!createdItem) {
      return NextResponse.json(
        { error: 'Failed to create item' },
        { status: 500 }
      )
    }

    return NextResponse.json({
      success: true,
      data: createdItem,
      message: 'Item created successfully'
    }, { status: 201 })

  } catch (error) {
    console.error('Error in POST /api/items:', error)
    
    // Handle specific error types
    if (error instanceof Error) {
      if (error.message.startsWith('DUPLICATE_ITEM:')) {
        const itemName = error.message.split(':')[1]
        return NextResponse.json(
          { error: `Item with name "${itemName}" already exists` },
          { status: 409 }
        )
      }
      
      if (error.message.startsWith('INVALID_REFERENCE:')) {
        return NextResponse.json(
          { error: 'Invalid reference (category or unit not found)' },
          { status: 400 }
        )
      }
    }

    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}