import { Service, Product } from "@/server/features/items/core/entities/Item";
import { Category } from "@/server/features/items/core/entities/Category";
import { NextRequest, NextResponse } from "next/server";
import { createItem, getUnitByCode ,getAllItems} from "@/server/features/items/infrastructure/persistence/ItemSupabase";

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const fpo_id = searchParams.get('fpo_id')

    if (!fpo_id) {
      return NextResponse.json(
        { error: 'FPO ID is required' },
        { status: 400 }
      )
    }

    // Get all items without pagination
    const allItems = await getAllItems(fpo_id)
    
    if (allItems === null) {
      return NextResponse.json(
        { error: 'Failed to fetch items' },
        { status: 500 }
      )
    }

    // Transform to ItemLite format for the frontend
    const itemsLite = allItems.map(item => ({
      id: item.id,
      name: item.name,
      categoryName: item.category.name,
      salePrice: item.salePrice,
      purchasePrice: item.type === 'product' ? (item as any).purchasePrice : 0
    }))

    return NextResponse.json({
      data: itemsLite,
      totalItems: itemsLite.length
    })

  } catch (error) {
    console.error('Error in GET /api/items:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const formData = body;
    const fpo_id = formData.fpo_id;

    // Validate required fields
    if (!formData.name || !formData.category || !formData.hsn_sac || 
        formData.salePrice === undefined || formData.salePriceInclusive === undefined || 
        formData.gstTaxPercent === undefined) {
      return NextResponse.json({ 
        error: "Missing required fields: name, category, hsn_sac, salePrice, salePriceInclusive, gstTaxPercent" 
      }, { status: 400 });
    }

    if (!fpo_id) {
      return NextResponse.json({ error: "FPO ID is required" }, { status: 400 });
    }

    // Create Category object with the selected category ID
    // Note: The category name will be populated from the database when creating the item
    const category = new Category(formData.category, ""); // Empty name will be filled by DB query

    let item;

    if (formData.type === "product") {
      if (!formData.unit) {
        return NextResponse.json({ error: "Unit is required for product" }, { status: 400 });
      }

      // Validate that the unit exists (either default or custom)
      const unitExists = await getUnitByCode(formData.unit);
      if (!unitExists) {
        return NextResponse.json({ 
          error: `Unit with code '${formData.unit}' does not exist` 
        }, { status: 400 });
      }

      // Create Unit object - use the validated unit data
      const unit = unitExists;

      item = new Product(
        "", // id will be generated by DB
        formData.name,
        category,
        formData.hsn_sac,
        formData.salePrice,
        formData.salePriceInclusive,
        formData.gstTaxPercent,
        formData.purchasePrice || 0,
        formData.purchasePriceInclusive || false,
        unit,
        formData.openingQuantity || 0,
        formData.openingStockDate ? new Date(formData.openingStockDate) : null,
        formData.mfgDate ? new Date(formData.mfgDate) : null,
        formData.expDate ? new Date(formData.expDate) : null,
        formData.barcode || null,
        formData.discount || null,
        formData.lowStockAlert || 0
      );
    } else {
      item = new Service(
        "", // id will be generated by DB
        formData.name,
        category,
        formData.hsn_sac,
        formData.salePrice,
        formData.salePriceInclusive,
        formData.gstTaxPercent
      );
    }

    // Debug log
    // console.log("Constructed item for createItem:", {
    //   name: item.name,
    //   type: item.type,
    //   category_id: item.category.id,
    //   unit_code: item instanceof Product ? item.unit.code : null,
    //   fpo_id: fpo_id,
    //   sendingdata: item
    // });

    const data = await createItem(item, fpo_id);
    
    if (!data) {
      return NextResponse.json({ 
        error: "item already exists " 
      }, { status: 500 });
    }

    return NextResponse.json({ 
      success: true, 
      data: data,
      message: "Item created successfully" 
    }, { status: 201 });

  } catch (error) {
    console.error("Error in POST /api/items:", error);
    return NextResponse.json({ 
      error: "Failed to create item", 
      details: error instanceof Error ? error.message : "Unknown error" 
    }, { status: 500 });
  }
}